version: "3.8"

services:

  makler-nodeparser:
    image: ghcr.io/${USER_NAME_LC}/makler-nodeparser:latest
    networks:
      - ht-net
    environment:
      - WS_ENDPOINT=ws://browserless:3000
      - API_BASE=${API_BASE}
      - NODE_ENV=production
    secrets:
      - makler_parser_api_token
    ports:
      - target: 35001
        published: 35001
        protocol: tcp
        mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:35001/test"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ht-net:
    external: true

secrets:
  makler_parser_api_token:
    external: true
